Web Programlama Dersi Proje Ödevi/Controllers/AracsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Web_Programlama_Dersi_Proje_Ödevi.Models;

namespace Web_Programlama_Dersi_Proje_Ödevi.Controllers
{
    public class AracsController : Controller
    {
        private SauCarEntities6 db = new SauCarEntities6();

        // GET: Aracs
        public ActionResult Index()
        {
            return View(db.Arac.ToList());
        }
        public ActionResult Araclar()
        {
            return View(db.Arac.ToList());
        }
        // GET: Aracs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Arac arac = db.Arac.Find(id);
            if (arac == null)
            {
                return HttpNotFound();
            }
            return View(arac);
        }

        // GET: Aracs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Aracs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AracId,AracModel,AracFiyat,AracTuru")] Arac arac)
        {
            if (ModelState.IsValid)
            {
                db.Arac.Add(arac);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(arac);
        }

        // GET: Aracs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Arac arac = db.Arac.Find(id);
            if (arac == null)
            {
                return HttpNotFound();
            }
            return View(arac);
        }

        // POST: Aracs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AracId,AracModel,AracFiyat,AracTuru")] Arac arac)
        {
            if (ModelState.IsValid)
            {
                db.Entry(arac).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(arac);
        }

        // GET: Aracs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Arac arac = db.Arac.Find(id);
            if (arac == null)
            {
                return HttpNotFound();
            }
            return View(arac);
        }

        // POST: Aracs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Arac arac = db.Arac.Find(id);
            db.Arac.Remove(arac);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Web Programlama Dersi Proje Ödevi/Controllers/SepetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Web_Programlama_Dersi_Proje_Ödevi.Models;

namespace Web_Programlama_Dersi_Proje_Ödevi.Controllers
{
    public class SepetsController : Controller
    {
        private SauCarEntities6 db = new SauCarEntities6();

        // GET: Sepets
        public ActionResult Index()
        {
            //if (Session["IsAdmin"] == null)
            //{
            //    var sepet = db.Sepet.Include(s => s.Arac).Include(s => s.User.UserName == Session["UserName"] );
            //    return View(sepet.ToList());
            //}
            //else
            //{
                var sepet = db.Sepet.Include(s => s.Arac).Include(s => s.User);
                return View(sepet.ToList());

            //}
           
        }

        // GET: Sepets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }
            Sepet sepet = db.Sepet.Find(id);
            if (sepet == null)
            {
                return HttpNotFound();
            }
            return View(sepet);
        }

        // GET: Sepets/Create
        public ActionResult Create()
        {
            ViewBag.SepetAracId = new SelectList(db.Arac, "AracId", "AracModel");
            ViewBag.SepetUserID = new SelectList(db.User, "UserId", "UserName");
            return View();
        }

        // POST: Sepets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SepetUserID,SepetAracId,SepetAlimTarihi,SepetTeslimTarihi,SepetID")] Sepet sepet)
        {
            if (ModelState.IsValid)
            {
                db.Sepet.Add(sepet);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SepetAracId = new SelectList(db.Arac, "AracId", "AracModel", sepet.SepetAracId);
            ViewBag.SepetUserID = new SelectList(db.User, "UserId", "UserName", sepet.SepetUserID);
            return View(sepet);
        }

        // GET: Sepets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sepet sepet = db.Sepet.Find(id);
            if (sepet == null)
            {
                return HttpNotFound();
            }
            ViewBag.SepetAracId = new SelectList(db.Arac, "AracId", "AracModel", sepet.SepetAracId);
            ViewBag.SepetUserID = new SelectList(db.User, "UserId", "UserName", sepet.SepetUserID);
            return View(sepet);
        }

        // POST: Sepets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SepetUserID,SepetAracId,SepetAlimTarihi,SepetTeslimTarihi,SepetID")] Sepet sepet)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sepet).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SepetAracId = new SelectList(db.Arac, "AracId", "AracModel", sepet.SepetAracId);
            ViewBag.SepetUserID = new SelectList(db.User, "UserId", "UserName", sepet.SepetUserID);
            return View(sepet);
        }

        // GET: Sepets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sepet sepet = db.Sepet.Find(id);
            if (sepet == null)
            {
                return HttpNotFound();
            }
            return View(sepet);
        }

        // POST: Sepets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Sepet sepet = db.Sepet.Find(id);
            db.Sepet.Remove(sepet);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Web Programlama Dersi Proje Ödevi/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Web_Programlama_Dersi_Proje_Ödevi.Models;

namespace Web_Programlama_Dersi_Proje_Ödevi.Controllers
{
    public class UsersController : Controller
    {
        private SauCarEntities6 db = new SauCarEntities6();

        // GET: Users
        public ActionResult Index()
        {
            return View(db.User.ToList());
        }

        // GET: Users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.User.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserId,UserName,UserPassword,IsAdmin")] User user)
        {
            if (ModelState.IsValid)
            {
                db.User.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.User.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserId,UserName,UserPassword,IsAdmin")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.User.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.User.Find(id);
            db.User.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Web Programlama Dersi Proje Ödevi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="img/fav.png">
    <!-- Author Meta -->
    <meta name="author" content="codepixer">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">

    <title>@ViewBag.Title</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <!-- ========= CSS  ========= -->
    <link rel="stylesheet" href="~/Dosyalar/css/linearicons.css">
    <link rel="stylesheet" href="~/Dosyalar/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Dosyalar/css/bootstrap.css">
    <link rel="stylesheet" href="~/Dosyalar/css/magnific-popup.css">
    <link rel="stylesheet" href="~/Dosyalar/css/nice-select.css">
    <link rel="stylesheet" href="~/Dosyalar/css/animate.min.css">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="~/Dosyalar/css/owl.carousel.css">
    <link rel="stylesheet" href="~/Dosyalar/css/main.css">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

</head>
<body>
<header id="header" id="home" style="background-color:black;">
 <div class="container">
     <div class="row align-items-center justify-content-between d-flex">

         @if (Session["IsAdmin"] != null)
         {
             <p>@Html.ActionLink(Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.AraclariGoruntule, "Index", "Aracs")</p>
             <p>@Html.ActionLink(Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.KullanicilariGörüntüle, "Index", "Users")</p>
         }
         <div id="logo">
             <img src="https://i.hizliresim.com/V9L45r.png" />
         </div>


         <nav id="nav-menu-container">
             <ul class="nav-menu">
                 <li>@Html.ActionLink(Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.AnaSayfa, "Index", "Home")</li>
                 <li>@Html.ActionLink(Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.Hakkimizda, "Hakkimizda", "Home")</li>
                 <li>@Html.ActionLink(Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.Araclar, "Araclar", "Aracs")</li>
                 <li>@Html.ActionLink(Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.Iletisim, "Iletisim", "Home")</li>
                 @if (Session["UserName"] == null)
                 {
                    <li>@Html.ActionLink(Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.GirisYap, "Giris", "GirisKayitIslemleri")</li>
                    <li>@Html.ActionLink(Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.KayitOl, "Kayit", "GirisKayitIslemleri")</li>
                 }

                 @if (Session["UserName"] != null)
                 {
                    <li>@Html.ActionLink(Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext .CikisYap+ "(  "+Session["UserName"] + "  )  ", "Cikis", "GirisKayitIslemleri")</li>
                    <li>@Html.ActionLink(Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.SepetiListele, "Index", "Sepets")</li>
                 }
                 <li><a href="@Url.Action("Sec","Language",new { LanguageAbbrevation  = "tr"},null)"><img src="https://i.hizliresim.com/QLYXmr.png"></a></li>
                 <li><a href="@Url.Action("Sec","Language",new { LanguageAbbrevation = "en"},null)"><img src="https://i.hizliresim.com/nQmPn1.png"></a></li>
             </ul>
         </nav>
     </div>
 </div>
</header>

    @RenderBody()


 <footer class="footer-area section-gap" style="background-color:black; color:gray">
   <div class="container">
     <div class="row">
         <p class="mt-50 mx-auto footer-text col-lg-12">
              &copy; @DateTime.Now.Year made with Emrullah Karakoç - Ahmet Can Örten
             <br />
         </p>
     </div>
   </div>
 </footer>

</body>
</html>